<?= $this->form ?>

<script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/controle_inclusoes.js' ?>"></script>

<script>
    $(function() {
        form.iniForm();
        controle.iniPeriodoCalendario('<?= $this->baseUrl() . "/imagens/calendar.png" ?>');
        /*$('#data_inicio, #data_termino').datepicker({
            buttonText: "Clique para selecionar uma data",
            showOn: "button",
            buttonImageOnly: true,
            buttonImage: '<?= $this->baseUrl() . "/imagens/calendar.png" ?>'
        });*/
    });
</script>
