<?php if ($this->aluno instanceof Application_Model_Aluno): ?>
    <h2>Informações do Aluno</h2>
    
    <table class="form-dados" style="width: 20%;">
        <tr>
            <th>Nome: </th><td><?= $this->aluno->getNomeAluno() ?></td>
        </tr>
        <tr>
            <th>CPF: </th><td><?= $this->aluno->getCpf() ?></td>
        </tr>
    </table>
    
    <?= $this->form ?>
    
    <script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/controle_inclusoes.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>
    <script>
        $(function() {
            controle.formDesligamento('<?= $this->baseUrl() . "/imagens/calendar.png" ?>');
            form.iniForm('');
        });
    </script>

    
 <?php else: ?>
    <p>Aluno não encontrado, ou ele já foi desligado do projeto</p>
   
<?php endif; ?>